### PR TITLE
Front end fixes

### PR DESCRIPTION
**Pull request by sanketd617**
Fixed frontend issues mentioned in issue #129

### CODE REVIEW

**Comment by Gabsii** [comment]
@sanketd617 could you add the footer from the login page too?

**Comment by sanketd617** [comment]
@Gabsii sure. I'll update it.

**Comment by Gabsii** [comment]
@sanketd617 Sorry I think you misunderstood me ^^ I wanted the footer from the login page on the policy page, not on the join page

**Comment by Gabsii** [comment]
I'll close this PR since it was idle for quite a while now.

**Pull request closed without merging**
