### PR TITLE
Removes Websocket from the Backend/Frontend

### PR DESCRIPTION
**Pull request by Michiocre**
Now everything is made possible with http requests

### CODE REVIEW

**Comment by Gabsii** [comment]
shooketh

**Comment by Michiocre** [comment]
I han mir denkt i merge scho mol mit dina neuen branches und jetzt crashed da build ba mir oh, :(

**Comment by Michiocre** [comment]
Merge Ready

**Comment by Michiocre** [comment]
Deprecated see #227

**Pull request closed without merging**
